backend:
  name: github
  repo: NikeTao-hub/NikeTao-hub.github.io
  branch: main
  base_url: https://oauth.niketao.com
  auth_endpoint: /auth

site_domain: niketao.com
media_folder: "static/images/uploads"
public_folder: "/images/uploads"


collections:

  - name: posts
    label: 文章
    folder: content/post
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:

      - name: title
        label: 标题
        widget: string

      - name: date
        label: 日期
        widget: datetime

      - name: body
        label: 正文
        widget: markdown